server {
    listen 80;
    listen [::]:80;
    server_name hackathon.shcyr.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name hackathon.shcyr.com;

    access_log /var/log/nginx/hackathon.shcyr.com.access.log;
    error_log /var/log/nginx/hackathon.shcyr.com.error.log warn;
    server_tokens off;
    client_max_body_size 1m;

    ssl_certificate /etc/letsencrypt/live/hackathon.shcyr.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hackathon.shcyr.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000" always;

    location / {
        proxy_pass http://127.0.0.1:8788;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 60s;
    }
}
